---
event_model_prior:
    dirichlet_process:
        parameters:
            concentration:
                value:      1.0
                estimate:   false

#event_time_prior:
#    gamma_distribution:
#        shape: 1.0
#        scale: 0.05
#        # Exponential(rate = 2 * birth_rate = 20)

event_time_prior:
  exponential_distribution:
    rate: 20.0 # lambda/waiting time = birth rate of 10 * 2 tips

mcmc_settings:
    chain_length: 75000
    sample_frequency: 50

operator_settings:
    auto_optimize: true
    auto_optimize_delay: 1000
    operators:
        ModelOperator:
            weight: 0.0
        TimeSizeRateMixer:
            weight: 3.0
            scale: 0.02
        TimeSizeRateScaler:
            weight: 0.0
            scale: 0.02
        EventTimeScaler:
            weight: 1.0
            scale: 0.02

global_comparison_settings:
    ploidy: 1
    genotypes_are_diploid: false
    markers_are_dominant: false
    population_name_delimiter: "_"
    population_name_is_prefix: true
    constant_sites_removed: false
    equal_population_sizes: false
    parameters:
        population_size:
            value: 0.002
            estimate: true
            prior:
                gamma_distribution:
                    shape: 5.0
                    scale: 0.0004
                    offset: 0.0
        freq_1:
            value: 0.5
            estimate: false
        mutation_rate:
            value: 1.0
            estimate: false
    operators:
        RootPopulationSizeScaler:
            weight: 1.0
            scale: 0.05
        LeafPopulationSizeScaler:
            weight: 1.0
            scale: 0.05
        TimeRootSizeMixer:
            weight: 3.0
            scale: 0.05

comparisons:
- comparison:
    path: "dummy-alignment.nex"
